### ISSUE TITLE
Be able to edit and sync files in the common-resources foulder

### ISSUE THREAD

**Issue by erydberg** [digexp/dxsync#1]
We have a lot of css and js in the common-resources-folder in webdav. It would be nice to be able to edit and sync those files as well.

**Comment by hesmer-ibm** [comment]
This is a great suggestion. Luckily you are able to do this through a special .settings file. I will add an article to the wiki that describes this and reference that here in the issue once done

**Comment by hesmer-ibm** [comment]
I created a new wiki page. Here is the link:
https://github.com/digexp/dxsync/wiki/9.1.-Synchronize-the-common-resources-folder

Closing as resolved
