### ISSUE TITLE
does filterRegex add to or replace the list of files to ignore?

### ISSUE THREAD

**Issue by dcacy** [digexp/dxsync#3]
I saw in the wiki that the tool ignores certain files by default. I want to also ignore files which start with a period.  Do I just add a line like

"filterRegex":".$"

or will that overwrite the existing list, which the documentation says is

^\.|~$|.bak$|.resolve$|.delete$|.conflict$

**Comment by mburati** [comment]
Darren,
The best part about an open project like this is that you can see the source to double check questions, answers you're given and to verify what it's really doing with such config.

dxsync run    will spit out the configuration properties to the console when it runs, so you can see what config setting it's using there after you make changes.

In a simple test I did, adding that configuration property explicitly to a .settings file for one of my themes and giving it different values than the default, I see it log the new/different values when it runs and not a merger of the default with the explicit settings.

Look in lib/utils.js and you can see where it both returns the default config settings and where it reads the config.    Looking in lib/main.js  you can see that it reads the config file and then walks it and for each known config property that is still undefined, it looks up the value of that property from the defaults,  so the defaults are replaced by explicit settings, not merged on an individual property value basis.

Also check lib/utils.js for the syntax of that config property for use in the .settings file (eg, backslash itself is escaped by another backslash for use in the json based config), for example:

		"filterRegex": "^\\.|~$|.bak$|.resolve$|.delete$|.conflict$",

I hope that info helps,
..Mike Burati 
The postings on this site are my own and do not necessarily represent the positions, strategies, or opinions of IBM.

**Comment by mburati** [comment]
Closing this issue as it turned out it was ignoring the file Darren wanted to ignore for cmdline dxsync and he was actually having an issue with dxdashboard so he re-asked the question to that team.
