### ISSUE TITLE
Improper Toast Notification Text

### ISSUE THREAD

**Issue by AshfaqMemon** [digexp/dxsync#7]
When I am opening Action Center to see the Notification, the notification group text is toast. It should be something like "IBM Digital Sync" or something useful.
![screenshot 22](https://cloud.githubusercontent.com/assets/12150952/19150674/b8c514fa-8be5-11e6-8c63-0c23214225ee.png)

**Comment by ThomasHurek** [comment]
Fixed with latest version here: https://github.com/hcl-dx/dxsync
