### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by jimartin7** [digexp/dxsync#9]
Hi,

When I try to install I have the following error:

C:\Users\IBM_ADMIN>cd C:\Instalaciones\DXSyncCLI-1.0.2

C:\Instalaciones\DXSyncCLI-1.0.2>install.cmd

C:\Instalaciones\DXSyncCLI-1.0.2>npm -g --production --no-optional install
npm WARN deprecated graceful-fs@3.0.6: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'n
 the tree.
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
C:\Users\IBM_ADMIN\AppData\Roaming\npm\dxsync -> C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\dxsync\bin\dxsync

> dxsync@1.0.2 postinstall C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\dxsync
> node postinstall.js

module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\dxsync\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Instalaciones\\nodejs\\node.exe" "C:\\Instalaciones\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "-g" "--production" "--no-optional" "install"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! dxsync@1.0.2 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dxsync@1.0.2 postinstall script 'node postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dxsync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dxsync
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dxsync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Instalaciones\DXSyncCLI-1.0.2\npm-debug.log

[npm-debug.zip](https://github.com/digexp/dxsync/files/790598/npm-debug.zip)

**Comment by zhanglouie** [comment]
it's sad that nobody is maintaining the code anymore??

**Comment by mburati** [comment]
Sorry,  as noted in issue #5 and as noted in the installation instructions in the readme, dxsync requires a specific version of node to install/run correctly, and unfortunately that version of Node (0.12) The author of this open source tool used some pre-built packages that require specific versions of Node, along with some dependencies that also had specific Node versions, with 0.12 being the common one that those were built/tested against.

A modified version of this dxsync tool is included with the newer Web Developer Toolkit for DX without the pre-compiled pathwatcher dependency, and thus runs on newer versions of Node (tested on Node 4.x).  See https://github.com/OpenNTF/WebDevToolkitForDx

The postings on this site are my own and do not necessarily represent the positions, strategies, or opinions of IBM.

**Comment by ThomasHurek** [comment]
This is fixed now - latest version supporting Node 12 is here: https://github.com/hcl-dx/dxsync
